version: '3.0'
services:
  magento22-dev:
    container_name: magento22-dev
    image: alexcheng/magento2:2.2.1
    environment:
      - MYSQL_HOST=db22-dev
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db22-dev
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento22-dev.docker:8086
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8086:80"
    extra_hosts:
      - "magento22-dev.docker:127.0.0.1"
    links:
      - db22-dev
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/app/code/Clearpay/Clearpay
    working_dir: /var/www/html/

  magento23-dev:
    container_name: magento23-dev
    image: alexcheng/magento2:latest
    environment:
      - MYSQL_HOST=db23-dev
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db23-dev
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento23-dev.docker:8087
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8087:80"
    extra_hosts:
      - "magento23-dev.docker:127.0.0.1"
    links:
      - db23-dev
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/app/code/Clearpay/Clearpay
    working_dir: /var/www/html/

  db22-dev:
    container_name: db22-dev
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db22-dev

  db23-dev:
    container_name: db23-dev
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db23-dev

  magento22-test:
    container_name: magento22-test
    image: alexcheng/magento2:2.2.1
    environment:
      - MYSQL_HOST=db22-test
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db22-test
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento22-test.docker:8085
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8085:80"
    extra_hosts:
      - "magento22-test.docker:127.0.0.1"
    links:
      - db22-test
    env_file:
      - .env
    working_dir: /var/www/html/

  magento23-test:
    container_name: magento23-test
    image: alexcheng/magento2:latest
    environment:
      - MYSQL_HOST=db23-test
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db23-test
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento23-test.docker:8084
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8084:80"
    extra_hosts:
      - "magento23-test.docker:127.0.0.1"
    links:
      - db23-test
    env_file:
      - .env
    working_dir: /var/www/html/

  db22-test:
    container_name: db22-test
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db22-test

  db23-test:
    container_name: db23-test
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db23-test

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:3.7.1
    ports:
      - "4444:4444"
    extra_hosts:
      - "magento22-test.docker:${DOCKERHOST}"
      - "magento23-test.docker:${DOCKERHOST}"
      - "magento22-dev.docker:${DOCKERHOST}"
      - "magento23-dev.docker:${DOCKERHOST}"
      - "magento24-dev.docker:${DOCKERHOST}"
      - "magento24-test.docker:${DOCKERHOST}"

  magento24-dev:
    container_name: magento24-dev
    image: 'docker.io/bitnami/magento:2-debian-10'
    ports:
      - '8088:80'
    extra_hosts:
      - "magento24-dev.docker:127.0.0.1"
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
      - MAGENTO_URL=http://magento24-dev.docker:8088
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  mariadb:
    container_name: mariadb
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    deploy:
      resources:
        limits:
          cpus: '0.20'  # Use at most 50% of one CPU core
          memory: 2000M  # Use at most 50 MB of RAM
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'

volumes:
  db-data:
  mariadb_data:
      driver: local
  elasticsearch_data:
    driver: local
  magento_data:
    driver: local

