version: '3.0'
services:
  magento20:
    image: alexcheng/magento2:2.2.1
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=magento2
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento20:8086
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8086:80"
    links:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/var/www/paylater
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=magento2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8087:80"
    links:
      - db
  selenium:
      image: selenium/standalone-chrome:3.7.1
      ports:
        - "4444:4444"
volumes:
  db-data:
