version: '3.0'
services:
  magento22-dev:
    container_name: magento22-dev
    image: alexcheng/magento2:2.2.1
    environment:
      - MYSQL_HOST=db22-dev
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db22-dev
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento22-dev.docker:8086
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8086:80"
    extra_hosts:
      - "magento22-dev.docker:127.0.0.1"
    links:
      - db22-dev
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/app/code/Clearpay/Clearpay
    working_dir: /var/www/html/

  magento23-dev:
    container_name: magento23-dev
    image: alexcheng/magento2:latest
    environment:
      - MYSQL_HOST=db23-dev
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db23-dev
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento23-dev.docker:8087
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8087:80"
    extra_hosts:
      - "magento23-dev.docker:127.0.0.1"
    links:
      - db23-dev
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/app/code/Clearpay/Clearpay
    working_dir: /var/www/html/

  magento24-dev:
    container_name: magento24-dev
    image: bitnami/magento:2.4.0
    environment:
      - MYSQL_HOST=db24-dev
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db24-dev
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento24-dev.docker:8088
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
      - MAGENTO_DATABASE_PASSWORD=password123
      - MAGENTO_USE_SECURE_ADMIN=no
    ports:
      - "8088:80"
    extra_hosts:
      - "magento24-dev.docker:127.0.0.1"
    links:
      - db24-dev
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/app/code/Clearpay/Clearpay
    working_dir: /var/www/html/

  db22-dev:
    container_name: db22-dev
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db22-dev

  db23-dev:
    container_name: db23-dev
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db23-dev

  db24-dev:
    container_name: db24-dev
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db24-dev

  magento22-test:
    container_name: magento22-test
    image: alexcheng/magento2:2.2.1
    environment:
      - MYSQL_HOST=db22-test
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db22-test
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento22-test.docker:8085
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8085:80"
    extra_hosts:
      - "magento22-test.docker:127.0.0.1"
    links:
      - db22-test
    env_file:
      - .env
    working_dir: /var/www/html/

  magento23-test:
    container_name: magento23-test
    image: alexcheng/magento2:latest
    environment:
      - MYSQL_HOST=db23-test
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db23-test
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento23-test.docker:8084
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8084:80"
    extra_hosts:
      - "magento23-test.docker:127.0.0.1"
    links:
      - db23-test
    env_file:
      - .env
    working_dir: /var/www/html/

  magento24-test:
    container_name: magento24-test
    image: bitnami/magento:2.4.0
    environment:
      - MYSQL_HOST=db24-test
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=db24-test
      - MAGENTO_LANGUAGE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=http://magento24-test.docker:8083
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=MyStore
      - MAGENTO_ADMIN_EMAIL=amdin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
    ports:
      - "8083:80"
    extra_hosts:
      - "magento24-test.docker:127.0.0.1"
    links:
      - db24-test
    env_file:
      - .env
    working_dir: /var/www/html/

  db22-test:
    container_name: db22-test
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db22-test

  db23-test:
    container_name: db23-test
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db23-test

  db24-test:
    container_name: db24-test
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=db24-test

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:3.7.1
    ports:
      - "4444:4444"
    extra_hosts:
      - "magento22-test.docker:${DOCKERHOST}"
      - "magento23-test.docker:${DOCKERHOST}"
      - "magento22-dev.docker:${DOCKERHOST}"
      - "magento23-dev.docker:${DOCKERHOST}"
      - "magento24-dev.docker:${DOCKERHOST}"
      - "magento24-test.docker:${DOCKERHOST}"

volumes:
  db-data:
