version: '2'

services:
    magento20:
        build:
          dockerfile: Dockerfile
          context: ./
        hostname: magento20
        domainname: paylater
        volumes:
          - "~/.composer:/home/magento2/.composer"
          - "./src:/paylater"
          - magento:/var/www/magento2
        environment:
          - MAGENTO_ADMIN_USER=admin
          - MAGENTO_ADMIN_PASSWORD=password123
          - MAGENTO_BACKEND_PATH=admin
          - MAGENTO_CRON_RUN=0
          - MAGENTO_DI_COMPILE=0
          - MAGENTO_DOWNLOAD_SOURCES_CLOUD=0
          - MAGENTO_DOWNLOAD_SOURCES_COMPOSER=1
          - MAGENTO_EDITION=ce
          - MAGENTO_GRUNT_COMPILE=0
          - MAGENTO_SAMPLE_DATA_INSTALL=1
          - MAGENTO_STATIC_CONTENTS_DEPLOY=0
          - MAGENTO_USE_SOURCES_IN_HOST=0
          - MAGENTO_WARM_UP_STOREFRONT=1
          - MAGENTO_VERSION=
          - USE_ELASTICSEARCH=0
          - USE_RABBITMQ=0
          - USE_REDIS_CACHE=0
          - USE_REDIS_FULL_PAGE_CACHE=0
          - USE_REDIS_SESSIONS=0
          - USE_SHARED_WEBROOT=
          - USE_UNISON_SYNC=0
          - USE_VARNISH=0
        env_file:
          - ./.env.dist
          - ./.env
        extra_hosts:
          - "magento20:127.0.0.1"
        ports:
          - "1748:80"
    db:
        image: mysql:5.6
        env_file:
          - ./.env.dist
          - ./.env
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento2
        ports:
          - "3306:3306"

    selenium:
        image: selenium/standalone-chrome:3.7.1
        ports:
          - "4444:4444"

volumes:
  magento:
